"""new models: huisjes en boekingen

Revision ID: 68e60a931ac8
Revises: ae172b316181
Create Date: 2026-03-30 18:32:41.751714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e60a931ac8'
down_revision = 'ae172b316181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('huisjes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personen', sa.Integer(), nullable=True),
    sa.Column('weekprijs', sa.Float(), nullable=True),
    sa.Column('beschrijving', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('huisjes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_huisjes_personen'), ['personen'], unique=False)
        batch_op.create_index(batch_op.f('ix_huisjes_weekprijs'), ['weekprijs'], unique=False)

    op.create_table('boekingen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gast_id', sa.Integer(), nullable=True),
    sa.Column('huis_id', sa.Integer(), nullable=True),
    sa.Column('weeknummer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gast_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['huis_id'], ['huisjes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boekingen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boekingen_weeknummer'), ['weeknummer'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boekingen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boekingen_weeknummer'))

    op.drop_table('boekingen')
    with op.batch_alter_table('huisjes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_huisjes_weekprijs'))
        batch_op.drop_index(batch_op.f('ix_huisjes_personen'))

    op.drop_table('huisjes')
    # ### end Alembic commands ###
