"""adding images houses

Revision ID: fb6cf21b8172
Revises: 68e60a931ac8
Create Date: 2026-03-30 19:28:31.769338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6cf21b8172'
down_revision = '68e60a931ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('huisjes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('afbeelding', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('huisjes', schema=None) as batch_op:
        batch_op.drop_column('afbeelding')

    # ### end Alembic commands ###
